version: '3.8'

services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seascope
    entrypoint: php artisan octane:frankenphp --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - .env
