FROM composer:latest

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app
COPY . .

RUN composer install --no-dev --optimize-autoloader && \
    php artisan key:generate && \
    chmod -R 777 storage bootstrap/cache
