version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_URL=http://localhost:8000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=seascope
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - OCTANE_SERVER=swoole
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: seascope
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 5
            timeout: 5s

volumes:
    db_data:
