version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_URL=http://localhost:8000
            - DB_CONNECTION=mysql
            - DB_HOST=192.168.101.130  # Gunakan 'host.docker.internal' jika di Windows/Mac
            - DB_PORT=3306
            - DB_DATABASE=seascope
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            db:
                condition: service_healthy
